# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EvalStatSlow <- function(X, s, t, optimization = "L2") {
    .Call(`_OCBS_EvalStatSlow`, X, s, t, optimization)
}

#' Leading NA
#'
#' This function returns a logical vector identifying if
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An integer vector
#' @export
MaxStats <- function(X, optimization = "L2", method = "advanced", circular = TRUE, min_seg = 2L) {
    .Call(`_OCBS_MaxStats`, X, optimization, method, circular, min_seg)
}

PermTest <- function(X, boundary, cand_stat, optimization, method, alpha, nr_perms = 10000L, circular = TRUE, min_seg = 2L) {
    .Call(`_OCBS_PermTest`, X, boundary, cand_stat, optimization, method, alpha, nr_perms, circular, min_seg)
}

#' Leading NA
#'
#' This function returns a logical vector identifying if
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An integer vector
#' @keywords internal
#' @export
#'
StoppingBoundary <- function(nr_perms = 10000L, alpha = 0.01, eta_star = 0.0005) {
    .Call(`_OCBS_StoppingBoundary`, nr_perms, alpha, eta_star)
}

